name: 'OL Post Settings'
type: module
description: 'OL Post Settings'
core_version_requirement: ^9
package: 'OL App'

# Information added by Drupal.org packaging script on 2021-05-20
version: '2.0.0-alpha7'
project: 'openlucius'
datestamp: 1621518109
